kind: pipeline
type: docker
name: hugo-website-ci

# --- Variables & Secrets ---
env: &env
  ENV: dev
  PROD_BASE_URL: http://restaurant-vbucket.s3-website-us-east-1.amazonaws.com/
  STAGING_BASE_URL: http://staging-restaurant-vbucket.s3-website-us-east-1.amazonaws.com
  RELEASE_S3_BUCKET: release-restaurant-vbucket
  AWS_SESSION_TOKEN:
    from_secret: aws_session_token
  AWS_ACCESS_KEY_ID:
    from_secret: aws_access_key_id
  AWS_SECRET_ACCESS_KEY:
    from_secret: aws_secret_access_key

# --- Déclencheurs (Triggers) ---
trigger:
  event:
    - push

# --- Étapes de la Pipeline (Steps) ---
steps:
  # Étape 1 : Build du site statique Hugo
  - name: hugo-build
    image: peaceiris/hugo:v0.124.1
    pull: if-not-exists
    environment:
      <<: *env
    commands:
      - hugo --minify --baseURL $PROD_BASE_URL
    when:
      event:
        - push
      branch: 
        - main
        - master

  # Étape 2 : Empaquetage et déploiement de la release
  - name: package-and-deploy-release
    image: amazon/aws-cli:latest
    pull: if-not-exists
    environment:
      <<: *env
    commands:
      - yum install -y zip
      - yum install -y gzip
      - yum install -y tar
      - export RELEASE_VERSION=$(echo $DRONE_COMMIT_SHA | cut -c 1-8)
      - export ARCHIVE_NAME="hugo-build-${RELEASE_VERSION}.tar.gz"
      - tar -czf ${ARCHIVE_NAME} -C ./public .
      - echo "Téléversement de l'archive vers s3://${RELEASE_S3_BUCKET}/"
      - aws s3 cp ${ARCHIVE_NAME} s3://${RELEASE_S3_BUCKET}/
    when:
      event:
        - push
      # CORRECTION 2 : Ajout de la condition sur la branche pour la cohérence.
      branch:
        - main
        - master