---
kind: pipeline
type: docker
name: hugo-website-ci

# --- Déclencheurs (Triggers) ---
# Cette pipeline se déclenchera uniquement sur les pushs vers la branche 'main'.
trigger:
  branch:
    - main
    - master
  event:
    - push

# --- Variables & Secrets ---
env: &env
  BASE_URL: http://restaurant-vbucket.s3-website-us-east-1.amazonaws.com/
  AWS_SESSION_TOKEN:
    from_secret: aws_session_token
  AWS_ACCESS_KEY_ID:
    from_secret: aws_access_key_id
  AWS_SECRET_ACCESS_KEY:
    from_secret: aws_secret_access_key

# --- Étapes de la Pipeline (Steps) ---
steps:
  # Étape 1 : Build du site statique Hugo
  - name: hugo-build
    image: peaceiris/hugo:v0.124.1 # Utilisation d'une version plus récente et populaire
    pull: if-not-exists
    environment:
      <<: *env
    commands:
      # Génère le site statique dans le dossier 'public'
      - hugo --minify --baseURL $BASE_URL
    when:
      event:
        - push

  # Étape 2 : Déploiement sur AWS S3
  - name: publish-website-s3
    image: amazon/aws-cli
    environment:
      <<: *env
    commands:
      - export AWS_DEFAULT_REGION="us-east-1"
      - aws s3 sync public/ s3://restaurant-vbucket/ --delete --acl public-read --exclude ".DS_Store"
    when:
      event: push
      branch: master