kind: pipeline
type: docker
name: hugo-website-ci

# --- Variables & Secrets ---
env: &env
  ENV: dev
  PROD_BASE_URL: http://restaurant-vbucket.s3-website-us-east-1.amazonaws.com/
  STAGING_BASE_URL: http://staging-restaurant-vbucket.s3-website-us-east-1.amazonaws.com
  RELEASE_S3_BUCKET: release-restaurant-vbucket
  AWS_SESSION_TOKEN:
    from_secret: aws_session_token
  AWS_ACCESS_KEY_ID:
    from_secret: aws_access_key_id
  AWS_SECRET_ACCESS_KEY:
    from_secret: aws_secret_access_key

# --- Déclencheurs (Triggers) ---
trigger:
  event:
    - push

# --- Étapes de la Pipeline (Steps) ---
steps:
  # Étape 1 : Build du site statique Hugo
  - name: hugo-build
    image: peaceiris/hugo:v0.124.1
    pull: if-not-exists
    environment:
      <<: *env
    commands:
      - hugo --minify --baseURL $PROD_BASE_URL
    when:
      event:
        - push
      branch: 
        - main
        - master

  # Étape 2 : Empaquetage et déploiement de la release
  - name: package-and-deploy-release
    image: amazon/aws-cli:latest
    pull: if-not-exists
    environment:
      <<: *env
    commands:
      # Installer 'tar' car il n'est pas dans l'image
      - yum install -y tar
      - yum install -y gzip

      # CORRECTION : Créer un identifiant de version robuste
      - export
      - export ARCHIVE_NAME="hugo-build-${CI_COMMIT_SHA}.tar.gz"

      # Créer l'archive tar.gz
      - tar -czf ${ARCHIVE_NAME} public/
      - echo hugo-build-${CI_BUILD_NUMBER}.tar.gz
      - aws s3 cp ${ARCHIVE_NAME} s3://${RELEASE_S3_BUCKET}/
    when:
      event:
        - push
      branch:
        - main
        - master